"""empty message

Revision ID: 1e602f205425
Revises: 0486459b49bb
Create Date: 2022-09-29 16:17:39.799975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e602f205425'
down_revision = '0486459b49bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defaulter', sa.Column('arrears', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defaulter', 'arrears')
    # ### end Alembic commands ###
