"""empty message

Revision ID: 2e3e3e5f5af5
Revises: 1e602f205425
Create Date: 2022-09-29 16:24:21.236975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3e3e5f5af5'
down_revision = '1e602f205425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defaulter', sa.Column('arrears', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defaulter', 'arrears')
    # ### end Alembic commands ###
