"""empty message

Revision ID: 3f7e750509a0
Revises: b6c2f79f51c0
Create Date: 2022-01-07 22:49:05.529453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7e750509a0'
down_revision = 'b6c2f79f51c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('defaulter_name_key', 'defaulter', type_='unique')
    op.drop_constraint('defaulter_telephone_key', 'defaulter', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('defaulter_telephone_key', 'defaulter', ['telephone'])
    op.create_unique_constraint('defaulter_name_key', 'defaulter', ['name'])
    # ### end Alembic commands ###
